apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.serviceName }}
  labels:
    app: frontend
    {{- include "rentiq.labels" . | nindent 4 }}
spec:
  selector:
    app: frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
