{{- if .Values.db.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  labels:
    {{- include "rentiq.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.db.persistence.storageClassName }}
  storageClassName: {{ .Values.db.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}
{{- end }}
