apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: {{ .Values.db.name }}
    {{- include "rentiq.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.db.name }}
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
