apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name }}
    {{- include "rentiq.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      initContainers:
        - name: wait-for-db
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          command:
            - sh
            - -c
            - |
              until pg_isready -h {{ .Values.db.name }} -p {{ .Values.db.port }} -U {{ .Values.db.user }}; do
                echo "Aguardando o banco de dados...";
                sleep 2;
              done
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.backend.name }}-config
            - secretRef:
                name: {{ .Values.backend.name }}-secret
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.healthCheckPath }}
              port: {{ .Values.backend.port }}
            initialDelaySeconds: {{ .Values.backend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.healthCheckPath }}
              port: {{ .Values.backend.port }}
            initialDelaySeconds: {{ .Values.backend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.liveness.periodSeconds }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
