apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    {{- include "rentiq.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-db
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          command:
            - sh
            - -c
            - |
              until pg_isready -h db -p {{ .Values.db.port }} -U {{ .Values.db.user }}; do
                echo "Aguardando o banco de dados...";
                sleep 2;
              done
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          readinessProbe:
            httpGet:
              path: /api/neighborhoods
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/neighborhoods
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
