apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    {{- include "rentiq.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.backend.jwtSecret | quote }}
  DATABASE_URL: "postgresql://{{ .Values.db.user }}:{{ .Values.db.password }}@db:{{ .Values.db.port }}/{{ .Values.db.database }}"
